name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pipeline:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Requirements
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build